[package]
name = "rust_rsa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primes = "0.3.0"
modinverse = "0.1.1"
mod_exp = "1.0.1"